#!/bin/bash
# layout
echo running xrandr...
xrandr --output DisplayPort-1 --off --output DisplayPort-0 --mode 1920x1080 --pos 1080x0 --rotate normal --output DVI-1 --mode 1920x1080 --pos 3000x0 --rotate right --output DVI-0 --off --output HDMI-0 --mode 1920x1080 --pos 0x0 --rotate left
echo did it run?
